### ISSUE TITLE
Ranged Combat "Aim" is not a SLOW action

### ISSUE THREAD

**Issue by james3dwards** [Saibot393/enhancedcombathud-t2k4e#1]
Hello.  on the HUD, Aim is showing as a SLOW action.  General Ranged Combat AIM is a FAST action.
The only slow AIM actions is Sniper Aim and Aim Howitzer or Morter.

See rules pg 56.

How can I change the HUD to reflect this?

**Comment by Saibot393** [comment]
The slow aim action is there to reflect the actions you mentioned, but i agree that it is a bit misleading having them there. I will be removing the aim action together with the enter/exit vehicle action to slim the ui down a bit.

**Comment by Saibot393** [comment]
Changed with v1.0.1
