### ISSUE TITLE
T2K - Reload Action Automation

### ISSUE THREAD

**Issue by SerotoninRonin** [Saibot393/enhancedcombathud-t2k4e#2]
When using the Reload Action you have nicely included it would be good for the success/failure to actually trigger a reload of the currently held weapon with the ability to choose from a drop down of stored ammo in the inventory.

**Comment by Saibot393** [comment]
Good idea, i will include it as a per client option. It will probably work similar to the gear button.

**Comment by SerotoninRonin** [comment]
I suppose the success or failure of the roll will mark off a Fast or Slow action accordingly but it will always be reloaded whether you fail or not.

**Comment by Saibot393** [comment]
The action is now automated with v1.1.0
