### ISSUE TITLE
Weapon Stat Indicator

### ISSUE THREAD

**Issue by SerotoninRonin** [Saibot393/enhancedcombathud-t2k4e#4]
The weapon Action button shows a top left corner number.  In this case it says "0".  The weapon in question doesn't have a stat that is 0.
![image](https://github.com/Saibot393/enhancedcombathud-t2k4e/assets/95154695/447db1ec-bb32-496a-835b-047bb1b985cc)

If I equip the grenade it changes to 3 which seems to be the range. 
![image](https://github.com/Saibot393/enhancedcombathud-t2k4e/assets/95154695/3c3104d3-5668-4394-8ea9-149dfd7d25c8)
What is this corner stat supposed to indicate? Range?

**Comment by Saibot393** [comment]
The indicator should show the amount of compatible ammunition (or quantity in case of explosives)

**Comment by SerotoninRonin** [comment]
Yeah that doesn't seem to be tracking for firearms.  I have 3 grenades in this example.  
The quantity of the grenades as you point out tracks, however neither the quantity of the AKM (ie 1) or the amount of available ammo is tracking against the "0"
![image](https://github.com/Saibot393/enhancedcombathud-t2k4e/assets/95154695/0d51770d-795c-4a2e-a14c-0939a6b4b0e7)

**Comment by Saibot393** [comment]
The tracker will only work if the ammo is set in the "Ammo" field of the weapon, that seems to work in my test world

**Comment by SerotoninRonin** [comment]
Yeah that doesn't seem to track in my install.

![image](https://github.com/Saibot393/enhancedcombathud-t2k4e/assets/95154695/ab745e8a-14b9-43a2-bf19-ffed88b949c2)

The ammo is set as "7.62x39" and I have one loaded into the weapon and it's still saying 0

**Comment by Saibot393** [comment]
It currently only matches the ammo 1 to 1, i t should work if the ammo is set to "7.62x39mm, 30-round Mag". I will look into improving that in a future patch. I can however not get the data field "Magazine" to show up in my world.

**Comment by SerotoninRonin** [comment]
Yeah that's odd. The "Ammo" drop down doesn't stipulate the size of the magazines as there are several variations of each calibre, so you can't set it specifically to "7.62x39mm, 30-round Mag"

**Comment by Saibot393** [comment]
I was able to directly paste the name into the text box itself

**Comment by SerotoninRonin** [comment]
Ok that works.  The default settings in the T2K core don't give you options for the capacity of the magazines so it seems like Stefouch hasn't made that connection yet.

**Comment by Saibot393** [comment]
The loaded ammunition should now be correctly recognised with v1.1.0

**Comment by SerotoninRonin** [comment]
awesome work with the updates!

**Comment by Saibot393** [comment]
If you encounter any problems with the updates or have any more ideas or suggestions, feel free to reopen the issues or make a new one
